[[redirects]]
  from = "/api/notes"
  to = "https://applicationnotes.000webhostapp.com/api/notes"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}


  

  [build]
  functions = "my_functions" # netlify-lambda builds to this folder AND Netlify reads functions from here